server:
  port: 8600
  
spring:
  application:
    name: amount-service
    
  zipkin:    base-url: http://192.168.99.100:9411
  sleuth:    sampler:      probability: 1.0
    trace-id128: true
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
