server:
  port: 8600
  
spring:
    
  zipkin:    base-url: http://192.168.99.100:9411
  sleuth:    sampler:      probability: 1.0
    trace-id128: true
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8100/eureka
