server:
  port: 8700
  
spring:  main:    allow-bean-definition-overriding: true

security:
  oauth2:
    client:
      clientId: 52fc2d46-3405-486c-9f28-edb2f0b64292
      clientSecret: ZGU5OTczMDktYmU2MS00ZWM5LWFmOWMtYzVhZWU1M2YwYmZi
      accessTokenUri: https://eu-gb.appid.cloud.ibm.com/oauth/v4/cdbab5ea-62ff-4947-a631-88bbccdbc847/token
      userAuthorizationUri: https://eu-gb.appid.cloud.ibm.com/oauth/v4/cdbab5ea-62ff-4947-a631-88bbccdbc847/authorization
    resource:
      userInfoUri: https://eu-gb.appid.cloud.ibm.com/oauth/v4/cdbab5ea-62ff-4947-a631-88bbccdbc847/userinfo