server:
  port: 8800
  
spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
   
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true